/**
 * Data Dragon class tags and base attack range per champion, at the pinned version (M15.4).
 *
 * Generated by `scripts/ddragon-fixture.ts` from Data Dragon's `champion.json` at 16.19.1,
 * together with `fixtures/ddragon-16.19.1-champion.json`; `tags.test.ts` checks the two agree,
 * so a pin bump regenerates both. Do not edit by hand.
 *
 * Keyed by the numeric champion key (what `game_players.champion_id` and the client carry). Tags
 * keep Data Dragon's order, so the first is the primary class; class wars counts **any** tag
 * (decision R8). Plain data, no imports: client panels may read it.
 */

/** The six classes Data Dragon tags champions with. Class wars offers five (no Fighter). */
export type ChampionClassTag = 'Assassin' | 'Fighter' | 'Mage' | 'Marksman' | 'Support' | 'Tank';

export const CHAMPION_CLASS_TAGS: readonly ChampionClassTag[] = [
  'Assassin',
  'Fighter',
  'Mage',
  'Marksman',
  'Support',
  'Tank',
];

const CHAMPION_TAGS: Readonly<Record<number, readonly ChampionClassTag[]>> = {
  1: ['Mage', 'Support'], // Annie
  2: ['Fighter', 'Tank'], // Olaf
  3: ['Tank', 'Mage'], // Galio
  4: ['Mage', 'Marksman'], // TwistedFate
  5: ['Fighter', 'Tank'], // XinZhao
  6: ['Fighter', 'Tank'], // Urgot
  7: ['Assassin', 'Mage'], // Leblanc
  8: ['Mage', 'Fighter'], // Vladimir
  9: ['Mage', 'Support'], // Fiddlesticks
  10: ['Marksman', 'Mage'], // Kayle
  11: ['Fighter', 'Assassin'], // MasterYi
  12: ['Tank', 'Support'], // Alistar
  13: ['Mage'], // Ryze
  14: ['Tank', 'Fighter'], // Sion
  15: ['Marksman'], // Sivir
  16: ['Support', 'Mage'], // Soraka
  17: ['Marksman', 'Mage'], // Teemo
  18: ['Marksman', 'Assassin'], // Tristana
  19: ['Fighter', 'Tank'], // Warwick
  20: ['Tank', 'Mage'], // Nunu
  21: ['Marksman', 'Mage'], // MissFortune
  22: ['Marksman', 'Support'], // Ashe
  23: ['Fighter', 'Assassin'], // Tryndamere
  24: ['Fighter'], // Jax
  25: ['Support', 'Mage'], // Morgana
  26: ['Support', 'Mage'], // Zilean
  27: ['Tank', 'Mage'], // Singed
  28: ['Assassin', 'Mage'], // Evelynn
  29: ['Marksman', 'Assassin'], // Twitch
  30: ['Mage'], // Karthus
  31: ['Tank', 'Mage'], // Chogath
  32: ['Tank', 'Support'], // Amumu
  33: ['Tank'], // Rammus
  34: ['Mage'], // Anivia
  35: ['Assassin'], // Shaco
  36: ['Tank', 'Fighter'], // DrMundo
  37: ['Support', 'Mage'], // Sona
  38: ['Assassin', 'Mage'], // Kassadin
  39: ['Fighter', 'Assassin'], // Irelia
  40: ['Support', 'Mage'], // Janna
  41: ['Fighter'], // Gangplank
  42: ['Marksman', 'Mage'], // Corki
  43: ['Mage', 'Support'], // Karma
  44: ['Support', 'Tank'], // Taric
  45: ['Mage'], // Veigar
  48: ['Fighter', 'Tank'], // Trundle
  50: ['Mage', 'Support'], // Swain
  51: ['Marksman'], // Caitlyn
  53: ['Tank', 'Support'], // Blitzcrank
  54: ['Tank', 'Mage'], // Malphite
  55: ['Assassin', 'Mage'], // Katarina
  56: ['Fighter', 'Assassin'], // Nocturne
  57: ['Tank', 'Support'], // Maokai
  58: ['Fighter', 'Tank'], // Renekton
  59: ['Fighter', 'Tank'], // JarvanIV
  60: ['Assassin', 'Mage'], // Elise
  61: ['Mage', 'Support'], // Orianna
  62: ['Fighter', 'Tank'], // MonkeyKing
  63: ['Mage', 'Support'], // Brand
  64: ['Fighter', 'Assassin'], // LeeSin
  67: ['Marksman', 'Assassin'], // Vayne
  68: ['Fighter', 'Mage'], // Rumble
  69: ['Mage'], // Cassiopeia
  72: ['Tank', 'Fighter'], // Skarner
  74: ['Mage', 'Support'], // Heimerdinger
  75: ['Fighter', 'Tank'], // Nasus
  76: ['Assassin', 'Mage'], // Nidalee
  77: ['Fighter', 'Tank'], // Udyr
  78: ['Tank', 'Fighter'], // Poppy
  79: ['Fighter', 'Mage'], // Gragas
  80: ['Fighter', 'Assassin'], // Pantheon
  81: ['Marksman', 'Mage'], // Ezreal
  82: ['Fighter', 'Mage'], // Mordekaiser
  83: ['Fighter', 'Tank'], // Yorick
  84: ['Assassin'], // Akali
  85: ['Mage'], // Kennen
  86: ['Fighter', 'Tank'], // Garen
  89: ['Tank', 'Support'], // Leona
  90: ['Mage'], // Malzahar
  91: ['Assassin'], // Talon
  92: ['Fighter', 'Assassin'], // Riven
  96: ['Marksman', 'Mage'], // KogMaw
  98: ['Tank'], // Shen
  99: ['Mage', 'Support'], // Lux
  101: ['Mage', 'Support'], // Xerath
  102: ['Fighter', 'Tank'], // Shyvana
  103: ['Mage', 'Assassin'], // Ahri
  104: ['Marksman'], // Graves
  105: ['Assassin', 'Fighter'], // Fizz
  106: ['Fighter', 'Tank'], // Volibear
  107: ['Assassin', 'Fighter'], // Rengar
  110: ['Marksman', 'Mage'], // Varus
  111: ['Tank', 'Support'], // Nautilus
  112: ['Mage'], // Viktor
  113: ['Tank'], // Sejuani
  114: ['Fighter', 'Assassin'], // Fiora
  115: ['Mage'], // Ziggs
  117: ['Support', 'Mage'], // Lulu
  119: ['Marksman'], // Draven
  120: ['Fighter', 'Tank'], // Hecarim
  121: ['Assassin'], // Khazix
  122: ['Fighter', 'Tank'], // Darius
  126: ['Fighter', 'Marksman'], // Jayce
  127: ['Mage'], // Lissandra
  131: ['Fighter', 'Assassin'], // Diana
  133: ['Marksman', 'Assassin'], // Quinn
  134: ['Mage'], // Syndra
  136: ['Mage'], // AurelionSol
  141: ['Fighter', 'Assassin'], // Kayn
  142: ['Mage'], // Zoe
  143: ['Mage', 'Support'], // Zyra
  145: ['Marksman', 'Mage'], // Kaisa
  147: ['Support', 'Mage'], // Seraphine
  150: ['Fighter', 'Tank'], // Gnar
  154: ['Tank', 'Fighter'], // Zac
  157: ['Fighter', 'Assassin'], // Yasuo
  161: ['Mage', 'Support'], // Velkoz
  163: ['Mage', 'Support'], // Taliyah
  164: ['Fighter', 'Assassin'], // Camille
  166: ['Marksman', 'Assassin'], // Akshan
  200: ['Fighter'], // Belveth
  201: ['Tank', 'Support'], // Braum
  202: ['Marksman', 'Mage'], // Jhin
  203: ['Marksman'], // Kindred
  221: ['Marksman'], // Zeri
  222: ['Marksman'], // Jinx
  223: ['Tank', 'Support'], // TahmKench
  233: ['Fighter', 'Assassin'], // Briar
  234: ['Fighter', 'Assassin'], // Viego
  235: ['Support', 'Marksman'], // Senna
  236: ['Marksman', 'Assassin'], // Lucian
  238: ['Assassin'], // Zed
  240: ['Fighter'], // Kled
  245: ['Assassin', 'Mage'], // Ekko
  246: ['Assassin'], // Qiyana
  254: ['Fighter', 'Assassin'], // Vi
  266: ['Fighter'], // Aatrox
  267: ['Support', 'Mage'], // Nami
  268: ['Mage', 'Marksman'], // Azir
  350: ['Support', 'Mage'], // Yuumi
  360: ['Marksman', 'Assassin'], // Samira
  412: ['Support', 'Tank'], // Thresh
  420: ['Fighter', 'Tank'], // Illaoi
  421: ['Fighter', 'Tank'], // RekSai
  427: ['Support', 'Mage'], // Ivern
  429: ['Marksman'], // Kalista
  432: ['Support', 'Mage'], // Bard
  497: ['Support'], // Rakan
  498: ['Marksman'], // Xayah
  516: ['Tank'], // Ornn
  517: ['Mage', 'Assassin'], // Sylas
  518: ['Mage', 'Support'], // Neeko
  523: ['Marksman'], // Aphelios
  526: ['Tank', 'Support'], // Rell
  555: ['Support', 'Assassin'], // Pyke
  711: ['Mage'], // Vex
  777: ['Fighter', 'Assassin'], // Yone
  799: ['Fighter', 'Assassin'], // Ambessa
  800: ['Mage', 'Support'], // Mel
  804: ['Marksman'], // Yunara
  805: ['Assassin', 'Mage'], // Locke
  875: ['Fighter', 'Tank'], // Sett
  876: ['Fighter', 'Mage'], // Lillia
  887: ['Fighter'], // Gwen
  888: ['Support', 'Mage'], // Renata
  893: ['Mage', 'Assassin'], // Aurora
  895: ['Fighter', 'Assassin'], // Nilah
  897: ['Tank', 'Fighter'], // KSante
  901: ['Marksman', 'Mage'], // Smolder
  902: ['Support', 'Mage'], // Milio
  904: ['Fighter'], // Zaahen
  910: ['Mage', 'Support'], // Hwei
  950: ['Assassin', 'Fighter'], // Naafiri
};

const CHAMPION_ATTACK_RANGE: Readonly<Record<number, number>> = {
  1: 625, // Annie
  2: 125, // Olaf
  3: 150, // Galio
  4: 525, // TwistedFate
  5: 175, // XinZhao
  6: 350, // Urgot
  7: 525, // Leblanc
  8: 450, // Vladimir
  9: 480, // Fiddlesticks
  10: 175, // Kayle
  11: 175, // MasterYi
  12: 125, // Alistar
  13: 550, // Ryze
  14: 175, // Sion
  15: 500, // Sivir
  16: 550, // Soraka
  17: 500, // Teemo
  18: 550, // Tristana
  19: 125, // Warwick
  20: 125, // Nunu
  21: 550, // MissFortune
  22: 600, // Ashe
  23: 175, // Tryndamere
  24: 125, // Jax
  25: 450, // Morgana
  26: 550, // Zilean
  27: 125, // Singed
  28: 125, // Evelynn
  29: 550, // Twitch
  30: 450, // Karthus
  31: 125, // Chogath
  32: 125, // Amumu
  33: 125, // Rammus
  34: 600, // Anivia
  35: 125, // Shaco
  36: 125, // DrMundo
  37: 550, // Sona
  38: 150, // Kassadin
  39: 200, // Irelia
  40: 550, // Janna
  41: 125, // Gangplank
  42: 550, // Corki
  43: 525, // Karma
  44: 150, // Taric
  45: 550, // Veigar
  48: 175, // Trundle
  50: 525, // Swain
  51: 650, // Caitlyn
  53: 125, // Blitzcrank
  54: 125, // Malphite
  55: 125, // Katarina
  56: 125, // Nocturne
  57: 125, // Maokai
  58: 125, // Renekton
  59: 175, // JarvanIV
  60: 550, // Elise
  61: 525, // Orianna
  62: 175, // MonkeyKing
  63: 550, // Brand
  64: 125, // LeeSin
  67: 550, // Vayne
  68: 125, // Rumble
  69: 550, // Cassiopeia
  72: 150, // Skarner
  74: 550, // Heimerdinger
  75: 125, // Nasus
  76: 525, // Nidalee
  77: 125, // Udyr
  78: 125, // Poppy
  79: 125, // Gragas
  80: 175, // Pantheon
  81: 550, // Ezreal
  82: 175, // Mordekaiser
  83: 175, // Yorick
  84: 125, // Akali
  85: 550, // Kennen
  86: 175, // Garen
  89: 125, // Leona
  90: 500, // Malzahar
  91: 125, // Talon
  92: 125, // Riven
  96: 500, // KogMaw
  98: 125, // Shen
  99: 550, // Lux
  101: 525, // Xerath
  102: 150, // Shyvana
  103: 550, // Ahri
  104: 425, // Graves
  105: 175, // Fizz
  106: 150, // Volibear
  107: 125, // Rengar
  110: 575, // Varus
  111: 175, // Nautilus
  112: 525, // Viktor
  113: 150, // Sejuani
  114: 150, // Fiora
  115: 550, // Ziggs
  117: 550, // Lulu
  119: 550, // Draven
  120: 175, // Hecarim
  121: 125, // Khazix
  122: 175, // Darius
  126: 125, // Jayce
  127: 550, // Lissandra
  131: 150, // Diana
  133: 525, // Quinn
  134: 550, // Syndra
  136: 550, // AurelionSol
  141: 175, // Kayn
  142: 550, // Zoe
  143: 575, // Zyra
  145: 525, // Kaisa
  147: 525, // Seraphine
  150: 175, // Gnar
  154: 175, // Zac
  157: 175, // Yasuo
  161: 525, // Velkoz
  163: 525, // Taliyah
  164: 125, // Camille
  166: 500, // Akshan
  200: 150, // Belveth
  201: 125, // Braum
  202: 550, // Jhin
  203: 500, // Kindred
  221: 550, // Zeri
  222: 525, // Jinx
  223: 175, // TahmKench
  233: 125, // Briar
  234: 200, // Viego
  235: 600, // Senna
  236: 500, // Lucian
  238: 125, // Zed
  240: 125, // Kled
  245: 125, // Ekko
  246: 150, // Qiyana
  254: 125, // Vi
  266: 175, // Aatrox
  267: 550, // Nami
  268: 525, // Azir
  350: 425, // Yuumi
  360: 500, // Samira
  412: 450, // Thresh
  420: 125, // Illaoi
  421: 175, // RekSai
  427: 475, // Ivern
  429: 525, // Kalista
  432: 500, // Bard
  497: 300, // Rakan
  498: 525, // Xayah
  516: 175, // Ornn
  517: 175, // Sylas
  518: 550, // Neeko
  523: 550, // Aphelios
  526: 175, // Rell
  555: 150, // Pyke
  711: 550, // Vex
  777: 175, // Yone
  799: 125, // Ambessa
  800: 550, // Mel
  804: 575, // Yunara
  805: 125, // Locke
  875: 125, // Sett
  876: 325, // Lillia
  887: 150, // Gwen
  888: 550, // Renata
  893: 550, // Aurora
  895: 225, // Nilah
  897: 150, // KSante
  901: 550, // Smolder
  902: 525, // Milio
  904: 175, // Zaahen
  910: 550, // Hwei
  950: 125, // Naafiri
};

/** A champion's Data Dragon tags, primary first; `null` for a key the pin does not ship (unknown). */
export function championTags(id: number): readonly ChampionClassTag[] | null {
  return Object.hasOwn(CHAMPION_TAGS, id) ? (CHAMPION_TAGS[id] ?? null) : null;
}

/** A champion's base attack range (`stats.attackrange`); `null` for a key the pin does not ship. */
export function championAttackRange(id: number): number | null {
  return Object.hasOwn(CHAMPION_ATTACK_RANGE, id) ? (CHAMPION_ATTACK_RANGE[id] ?? null) : null;
}

/** Every key the table has, ascending. */
export function taggedChampionIds(): number[] {
  return Object.keys(CHAMPION_TAGS)
    .map(Number)
    .sort((a, b) => a - b);
}
