// Generated by apps/web/scripts/font-subsets.py (`pnpm --filter web font-subsets`). Do not edit by hand:
// the unicode-ranges below are read from the files' own cmaps.
import localFont from 'next/font/local';

/**
 * Every webfont the app loads, as CSS variables on <html> (the root layout). `docs/05-design.md`
 * section 4 and 4.1: Atkinson Hyperlegible Next for text, Martian Mono for numbers and role words, and
 * Archivo (its condensed `wdth` end) for the display face, each self-hosted, trimmed to the axis ranges
 * the app draws, and split by `unicode-range` into two files:
 *
 * - **core** (printable ASCII and the app's punctuation; display: upper case only), preloaded on every
 *   page: about 40 KB for all three, the only font bytes before LCP;
 * - **rest** (the rest of Google's latin + latin-ext: `Menaçe`, `Ramzyinhović`), never preloaded and
 *   fetched only when a glyph in its range is on screen.
 *
 * Each call is its own family, so `globals.css` lists core then rest in each stack, then a hand-measured
 * fallback face (`adjustFontFallback: false` here: next/font measures a face at its default instance,
 * not at the condensed widths the app draws). `display: 'swap'` everywhere: a friend opening the
 * WhatsApp link reads the teams in the fallback face rather than wait for a webfont.
 */
const textCore = localFont({
  src: './fonts/text-core.woff2',
  weight: '400 700',
  display: 'swap',
  preload: true,
  adjustFontFallback: false,
  declarations: [
    {
      prop: 'unicode-range',
      value:
        'U+0020-007E, U+00A0, U+00B1, U+00B7, U+00D7, U+2013-2014, U+2019, U+201C-201D, U+2022, U+2026, U+2039-203A, U+2212',
    },
  ],
  variable: '--font-text-core',
});

const textRest = localFont({
  src: './fonts/text-rest.woff2',
  weight: '400 700',
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
  declarations: [
    {
      prop: 'unicode-range',
      value:
        'U+00A1-00AC, U+00AE-00B0, U+00B2-00B4, U+00B6, U+00B8-00D6, U+00D8-0107, U+010A-0113, U+0116-011B, U+011E-0123, U+0126-0127, U+012A-012B, U+012E-0133, U+0136-0137, U+0139-013E, U+0141-0148, U+0150-0155, U+0158-015B, U+015E-0165, U+016A-016B, U+016E-017E, U+0192, U+0218-021B, U+0237, U+02C6-02C7, U+02C9, U+02DA, U+02DC-02DD, U+0304, U+0308, U+1E80-1E85, U+1E9E, U+1EF2-1EF3, U+2009, U+2018, U+201A, U+201E, U+2020-2021, U+2030, U+2044, U+20AC, U+20B9, U+2113, U+2122, U+2215',
    },
  ],
  variable: '--font-text-rest',
});

const monoCore = localFont({
  src: './fonts/mono-core.woff2',
  weight: '400 700',
  display: 'swap',
  preload: true,
  adjustFontFallback: false,
  declarations: [
    { prop: 'font-stretch', value: '75% 100%' },
    {
      prop: 'unicode-range',
      value:
        'U+0020-007E, U+00A0, U+00B1, U+00B7, U+00D7, U+2013-2014, U+2019, U+201C-201D, U+2022, U+2026, U+2039-203A, U+2191, U+2193, U+2212',
    },
  ],
  variable: '--font-mono-core',
});

const monoRest = localFont({
  src: './fonts/mono-rest.woff2',
  weight: '400 700',
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: 'font-stretch', value: '75% 100%' },
    {
      prop: 'unicode-range',
      value:
        'U+00A1-00B0, U+00B2-00B6, U+00B8-00D6, U+00D8-0107, U+010A-0113, U+0116-011B, U+011E-0123, U+0126-012B, U+012E-0133, U+0136-0148, U+014A-014D, U+0150-015B, U+015E-017E, U+018F, U+0192, U+019D, U+01CD-01CE, U+01E6-01E7, U+01FA-01FF, U+0218-021B, U+0232-0233, U+0237, U+0259, U+0272, U+02BC, U+02C6-02C7, U+02DA, U+02DC-02DD, U+0304, U+0308, U+1E0C-1E0D, U+1E24-1E25, U+1E62-1E63, U+1E6C-1E6D, U+1E80-1E85, U+1E92-1E93, U+1E9E, U+1EF2-1EF3, U+1EF8-1EF9, U+2002-2003, U+2011, U+2018, U+201A, U+201E, U+2020-2021, U+2030, U+2044, U+20AC, U+20B4, U+20BD, U+2122, U+A78B-A78C',
    },
  ],
  variable: '--font-mono-rest',
});

const displayCore = localFont({
  src: './fonts/display-core.woff2',
  weight: '800 900',
  display: 'swap',
  preload: true,
  adjustFontFallback: false,
  declarations: [
    { prop: 'font-stretch', value: '62% 70%' },
    {
      prop: 'unicode-range',
      value:
        'U+0020-0060, U+007B-007E, U+00A0, U+00B1, U+00B7, U+00D7, U+2013-2014, U+2019, U+201C-201D, U+2022, U+2026, U+2039-203A, U+2191, U+2193, U+2212',
    },
  ],
  variable: '--font-display-core',
});

const displayRest = localFont({
  src: './fonts/display-rest.woff2',
  weight: '800 900',
  display: 'swap',
  preload: false,
  adjustFontFallback: false,
  declarations: [
    { prop: 'font-stretch', value: '62% 70%' },
    {
      prop: 'unicode-range',
      value:
        'U+0061-007A, U+00A1-00B0, U+00B2-00B6, U+00B8-00D6, U+00D8-017F, U+018F, U+0192, U+019D, U+01A0-01A1, U+01AF-01B0, U+01C4-01DC, U+01E6-01E7, U+01EA-01EB, U+01FA-021B, U+022A-022D, U+0230-0233, U+0237, U+0259, U+0272, U+02B9-02BA, U+02BC, U+02C6-02C7, U+02C9, U+02DA, U+02DC-02DD, U+0304, U+0308, U+1E24-1E25, U+1E62-1E63, U+1E6C-1E6D, U+1E80-1E85, U+1E9E, U+1EF2-1EF9, U+2009, U+2010-2011, U+2015, U+2017-2018, U+201A, U+201E, U+2020-2021, U+2030, U+2032-2033, U+203E, U+2044, U+2052, U+20A1, U+20A3-20A4, U+20A6-20A7, U+20A9, U+20AB-20AD, U+20B1-20B2, U+20B5, U+20B9-20BA, U+20BC-20BD, U+2113, U+2122, U+2215, U+FEFF',
    },
  ],
  variable: '--font-display-rest',
});

/** The class list for <html>: defines the six variables and nothing else. */
export const fontVariables = [textCore, textRest, monoCore, monoRest, displayCore, displayRest]
  .map((font) => font.variable)
  .join(' ');
