"""Writes app/_og/metrics.ts: advance widths, per 1000 em, for the share cards' text and display faces.

M14.42 (scene-walk gap 11): Satori has no fit-to-width, so `Cards.tsx` shrinks a long name itself
before it would cut off, measuring with these tables. Run it again only if a TTF in app/_og/fonts
changes:

    python3 apps/web/scripts/og-metrics.py && pnpm exec biome format --write apps/web/app/_og/metrics.ts

Needs fontTools (pip install fonttools). Covers U+0020-U+017F (Basic Latin, Latin-1, Latin
Extended-A); anything else is measured at the face's widest advance, so an unknown glyph can only
make a name smaller, never cut it off.
"""

from pathlib import Path

from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent.parent
FONTS = ROOT / "app" / "_og" / "fonts"
FIRST, LAST = 0x20, 0x17F

FACES = {
    "TEXT_BOLD": "AtkinsonHyperlegibleNext-Bold.ttf",
    "TEXT_REGULAR": "AtkinsonHyperlegibleNext-Regular.ttf",
    "DISPLAY": "ArchivoCondensed62-Black.ttf",
}


def table(file: str) -> tuple[list[int], int]:
    font = TTFont(FONTS / file)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    hmtx = font["hmtx"]
    widths = []
    for code in range(FIRST, LAST + 1):
        glyph = cmap.get(code)
        widths.append(round(hmtx[glyph][0] * 1000 / upm) if glyph else -1)
    widest = max(w for w in widths if w >= 0)
    return [widest if w < 0 else w for w in widths], widest


lines = [
    "// Generated by apps/web/scripts/og-metrics.py from app/_og/fonts. Do not edit by hand.",
    "// Advance widths per 1000 em for U+0020-U+017F; anything else measures at the face's widest.",
    "",
    f"export const METRICS_FIRST = 0x{FIRST:x};",
    "",
]
for name, file in FACES.items():
    widths, widest = table(file)
    lines.append(f"/** {file} */")
    lines.append(f"export const {name}_WIDEST = {widest};")
    lines.append(f"export const {name}_WIDTHS: readonly number[] = [")
    for i in range(0, len(widths), 16):
        lines.append("  " + ", ".join(str(w) for w in widths[i : i + 16]) + ",")
    lines.append("];")
    lines.append("")

(ROOT / "app" / "_og" / "metrics.ts").write_text("\n".join(lines))
print("wrote app/_og/metrics.ts")
