-- 0019_group_keys_companion.sql (M13.3)
--
-- The commit that makes every companion-facing route and the rating fold work inside one group
-- (`02-milestones.md` M13.3, `04-decisions.md` 2026-10-03). `0018` added the per-group keys
-- beside the old ones so it could land with no app change; this drops the two old keys whose
-- last writer switched to the new ones in the same commit:
--
--   ratings         `(player_id, season_id)` -> `(group_id, player_id, season_id)`. One rating
--                   per person **per group**: from here a second group's games can no longer
--                   overwrite the first group's number.
--   fearless_state  the `id = 1` singleton -> one row per group (`fearless_state_group_id_key`,
--                   from 0018). The app now reads and writes it by `group_id`.
--
-- Two more changes ride along, both forced by the same switch:
--
--   companion_commands_one_create_lobby_idx  the Start-a-lobby lock (`0008`, M4.9) was global:
--                   one live `create_lobby` in the whole table. With start-a-lobby now aimed at
--                   one group's tokens (M13.3), a global lock would let one group's press refuse
--                   another group's for a minute. Same name, so the app's violation check
--                   (`CREATE_LOBBY_LOCK_INDEX`) is unchanged; now per `group_id`.
--   companion_tokens_add_membership         a token is only good while its player is a member of
--                   its group (M13.3: no membership is 403). Minting a token for a group is an
--                   admin's or the operator's act of making that player a host **there**, so the
--                   insert adds the `member` row when there is none -- the same rule 0018's
--                   backfill applied to every token holder, and the rule `mint-token --group`
--                   states. Insert only: deleting the membership afterwards still revokes the
--                   token, and `role` is never touched.
--
-- Unchanged on purpose: `games.lcu_game_id` and the live-party index on `lobbies.lcu_party_id`
-- stay global (a game belongs to exactly one group). The remaining old keys and the ten
-- temporary `group_id` defaults are M13.4's `0020`.
--
-- Never edit this file once it has been applied. Add a new numbered migration.

-- ---------------------------------------------------------------------------
-- ratings: the per-group key becomes the primary key
--
-- Not merely "drop the old primary key": `ratings` is in the `supabase_realtime` publication,
-- and a published table with no primary key (replica identity default) refuses every UPDATE.
-- So the old primary key goes, the 0018 unique constraint goes, and the same three columns come
-- back as the primary key. PostgREST's `on_conflict=group_id,player_id,season_id` infers it the
-- same way it inferred the unique constraint.
-- ---------------------------------------------------------------------------

alter table public.ratings drop constraint ratings_pkey;
alter table public.ratings drop constraint ratings_group_player_season_key;
alter table public.ratings
  add constraint ratings_pkey primary key (group_id, player_id, season_id);

comment on table public.ratings is
  'OpenSkill rating per player per group per season (M13: one rating per person per group). Balance on mu, leaderboard on ordinal.';

-- ---------------------------------------------------------------------------
-- fearless_state: one row per group
--
-- The `id = 1` check goes; `id` stays the primary key (the table is published, so it keeps a
-- replica identity) and gains an identity default so a new group's row (M13.5) is inserted with
-- `group_id` alone. The existing row keeps id 1; the identity starts after it.
-- ---------------------------------------------------------------------------

alter table public.fearless_state drop constraint fearless_state_id_check;
alter table public.fearless_state
  alter column id add generated by default as identity (start with 2);

comment on table public.fearless_state is
  'One fearless-draft cursor per group (M10, M13). The pool is unique champion_id values from the group''s Rift games with started_at > reset_at. Service role writes; anon reads.';
comment on column public.fearless_state.id is
  'Surrogate key (identity). The group''s row is found by group_id, which is unique (fearless_state_group_id_key).';

-- ---------------------------------------------------------------------------
-- The Start-a-lobby lock, per group
-- ---------------------------------------------------------------------------

drop index if exists public.companion_commands_one_create_lobby_idx;

create unique index companion_commands_one_create_lobby_idx
  on public.companion_commands (group_id, kind)
  where kind = 'create_lobby' and status in ('pending', 'sent');

comment on index public.companion_commands_one_create_lobby_idx is
  'M4.9, per group since M13.3: at most one create_lobby in pending or sent per group. The Start-a-lobby double-tap lock, as a constraint rather than a read. Released by ack, nack or the expiry sweep.';

-- ---------------------------------------------------------------------------
-- A token makes its player a member of its group
-- ---------------------------------------------------------------------------

create or replace function public.companion_token_add_membership() returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.group_memberships (group_id, player_id, role)
  values (new.group_id, new.player_id, 'member')
  on conflict (group_id, player_id) do nothing;
  return new;
end;
$$;

comment on function public.companion_token_add_membership() is
  'M13.3: a companion token is minted for a group, so its player is a member of that group. Adds the member row if there is none; never changes a role.';

revoke all on function public.companion_token_add_membership() from public, anon, authenticated;

create trigger companion_tokens_add_membership
  after insert on public.companion_tokens
  for each row execute function public.companion_token_add_membership();
