/**
 * `packages/lcu` is the only place in the repo that talks to the League client.
 * Lockfile discovery, the basic-auth HTTPS client, the WebSocket subscriber and the endpoint catalogue
 * live here. Nothing else may import `https`/`ws` or reach 127.0.0.1 (CLAUDE.md "Hard rules").
 *
 * Per-endpoint response schemas live in `schemas.ts`; each one marked verified is tested against the fixture
 * it was written from (`fixtures/<patch>/`). Rows still unverified in docs/03-lcu-reference.md have no schema.
 */

export { basicAuthHeader, buildUrl, httpBaseUrl, LCU_HOST, LCU_USER, wsBaseUrl } from './auth.js';
export {
  type HttpMethod,
  LcuClient,
  type LcuClientOptions,
  type LcuFailure,
  type LcuResponse,
  parseBody,
  type RawBody,
  type RawResponse,
} from './client.js';
export {
  canFill,
  fillPath,
  LIVE_CLIENT_DATA,
  MATCH_HISTORY_PAGE_TEMPLATE,
  matchHistoryPagePath,
  type PathParam,
  READ_ENDPOINTS,
  type ReadEndpoint,
  readEndpoint,
  WRITE_ENDPOINTS,
} from './endpoints.js';
export {
  diffTopLevelKeys,
  FIXTURES_DIR,
  type FixtureEnvelope,
  FixtureEnvelopeSchema,
  fixturePath,
  isShapeDiffEmpty,
  listPatchDirs,
  newestFixture,
  patchFromVersion,
  readFixture,
  type ShapeDiff,
  writeFixture,
} from './fixtures.js';
export {
  createLockfileDiscovery,
  type DiscoverLockfileOptions,
  type DiscoverLockfileResult,
  defaultLockfileCandidates,
  discoverLockfile,
  LOCKFILE_CANDIDATES_ENV,
  type LockfileAttempt,
  type LockfileCredentials,
  LockfileCredentialsSchema,
  type LockfileDiscovery,
  type LockfileDiscoveryOptions,
  type LockfileSource,
  lockfileCandidatesFromEnv,
  MACOS_LOCKFILE_PATH,
  type ParseLockfileResult,
  PROCESS_ARGS_PATH,
  PROCESS_LIST_PATH,
  parseLockfile,
  WINDOWS_LOCKFILE_PATH,
} from './lockfile.js';
export { consoleLogger, type LogFields, type Logger, silentLogger, verboseConsoleLogger } from './log.js';
export {
  isEogBot,
  isLobbyBot,
  type MapEogOptions,
  type MapMatchDetailOptions,
  type MapRankOptions,
  mapEog,
  mapLobby,
  mapMatchDetail,
  mapRank,
  matchDetailWinningSide,
  type NameCache,
  nameFromSummoner,
  RANK_QUEUE,
  type RiotIdName,
  type UnmappedTimelinePair,
} from './mapper.js';
export {
  type CommandLineCredentials,
  LEAGUE_UX_PROCESS_NAME,
  type LeagueProcess,
  lockfilePathFromExecutable,
  type ProcessLister,
  type ProcessListResult,
  parsePowerShellProcessList,
  parseUxCommandLine,
  parseWmicProcessList,
  resolveProcessLister,
  type WindowsProcessListerOptions,
  windowsProcessLister,
} from './processDiscovery.js';
export {
  type AliasLookup,
  AliasLookupSchema,
  BOT_PUUID,
  type CurrentSummonerMinimal,
  CurrentSummonerMinimalSchema,
  CurrentSummonerSchema,
  type CustomGameMutator,
  CustomGameMutatorSchema,
  type CustomGameQueues,
  CustomGameQueuesSchema,
  type CustomGameSubcategory,
  CustomGameSubcategorySchema,
  type EogPlayer,
  EogPlayerSchema,
  type EogPlayerStats,
  EogPlayerStatsSchema,
  type EogStatsBlock,
  EogStatsBlockSchema,
  type EogTeam,
  EogTeamSchema,
  GameflowPhaseSchema,
  type GameflowSession,
  GameflowSessionSchema,
  type GameflowTeamMember,
  GameflowTeamMemberSchema,
  type GameQueue,
  GameQueueSchema,
  GameQueuesSchema,
  GameVersionSchema,
  JsonArraySchema,
  type JsonObject,
  JsonObjectSchema,
  JsonValueSchema,
  KNOWN_GAMEFLOW_PHASES,
  KNOWN_TIERS,
  type KnownGameflowPhase,
  type LcuError,
  LcuErrorSchema,
  type Lobby,
  type LobbyInvitation,
  LobbyInvitationSchema,
  type LobbyMember,
  LobbyMemberSchema,
  LobbyMembersSchema,
  LobbySchema,
  type MatchDetail,
  MatchDetailSchema,
  type MatchGame,
  MatchGameSchema,
  type MatchHistoryList,
  MatchHistoryListSchema,
  type MatchHistoryMinimal,
  MatchHistoryMinimalSchema,
  type MatchParticipant,
  type MatchParticipantIdentity,
  MatchParticipantIdentitySchema,
  MatchParticipantSchema,
  type MatchParticipantStats,
  MatchParticipantStatsSchema,
  type MatchTeam,
  MatchTeamSchema,
  type RankedQueueEntry,
  RankedQueueEntrySchema,
  type RankedStats,
  RankedStatsSchema,
  type Summoner,
  SummonerSchema,
  type SystemBuilds,
  SystemBuildsSchema,
  type TeamId,
  TeamIdSchema,
} from './schemas.js';
export {
  isSensitiveUri,
  REDACTED,
  type ScrubbedDroppedFrame,
  type ScrubbedEvent,
  SENSITIVE_URI_PREFIXES,
  scrubDroppedFrame,
  scrubEvent,
  scrubText,
  scrubValue,
} from './scrub.js';
export {
  ALL_EVENTS_TOPIC,
  DEFAULT_HEARTBEAT_MS,
  DEFAULT_HEARTBEAT_TIMEOUT_MS,
  type FrameParseResult,
  HEARTBEAT_CLOSE_REASON,
  type LcuEvent,
  LcuEventFrameSchema,
  type LcuEventType,
  LcuEventTypeSchema,
  LcuSocket,
  type LcuSocketCloseInfo,
  type LcuSocketDroppedFrame,
  type LcuSocketEvents,
  type LcuSocketOptions,
  parseFrame,
  subscribeMessage,
  topicForUri,
  unsubscribeMessage,
} from './socket.js';
export {
  crossCheckTimelineRoles,
  EOG_STATS_BLOCK_URI,
  formatTimelineConfusion,
  MATCH_TIMELINE_ROLES,
  type MatchTimeline,
  matchTimelineKey,
  readTimelineEvidence,
  roleFromMatchTimeline,
  type TimelineConfusionRow,
  type TimelineCrossCheck,
  type TimelineEvidence,
  type TimelineObservation,
  timelinePairsSeen,
} from './timelineRoles.js';
export {
  DEFAULT_TLS_MODE,
  describeTlsMode,
  isTlsError,
  loadRiotRootCa,
  RIOT_ROOT_CA_PATH,
  type TlsConnectionOptions,
  type TlsMode,
  tlsConnectionOptions,
} from './tls.js';
export {
  assertLobbyWritePath,
  describeWriteResponse,
  isLobbyWritePath,
  isLobbyWriteVerified,
  LOBBY_WRITE_PATHS,
  LOBBY_WRITE_REFERENCE_ROW,
  LOBBY_WRITE_VERIFICATION,
  type LobbyWrite,
  type LobbyWriteKind,
  postSwitchSide,
  switchSidePath,
  type WriteVerification,
} from './writes.js';
